# Generated by Django 5.1.3 on 2024-11-24 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='capacidad_disponible',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='disponible',
        ),
        migrations.AddField(
            model_name='cita',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='gestion_citas.agenda'),
        ),
    ]
